name: APK_build
on:
  push:
    branches:
      - master

  pull_request:
    branches:
      -master

jobs:
  version_number:
    runs-on: macos-latest
    outputs:
      build_number: ${{steps.buildnumber.outputs.build_number }}
    steps:
      - name: Generate build number
        id: buildnumber
        uses: einaregilsson/build-number@v3
        with:
          token: ${{secrets.GH_TOKEN}}
      - name: Print new build number
        run: echo "Build number is $BUILD_NUMBER"
      - name: Current Directory
        run: pwd
      - name: Generating debug keystore and SHA1 key
        run: |
          mkdir /Users/runneradmin/.android
          keytool -genkey -dname "cn=Sandeep Jha, ou=IIITB, o=IIITB, l=Darbhanga, st=Bihar, c=IN" -keystore /Users/runneradmin/.android/debug.keystore -storepass android -alias AndroidDebugKey -keyalg RSA -keysize 4096 -validity 10000 -v
      - name: Displaying debug.keystore file
        run: keytool -list -v -keystore /Users/runneradmin/.android/debug.keystore -alias AndroidDebugKey -storepass android -keypass android


  flutter_test:
    name: Run flutter test and analyze
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: flutter pub get
#      - run: flutter analyze
#      - run: flutter test

  build_appbundle_apk:
    name: Build Flutter (Android)
    needs: [version_number,flutter_test]
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: "12.x"
      - uses: subosito/flutter-action@v1
        with:
          channel: "stable"
      - run: dart --version
      - run: flutter --version
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build appbundle
      - run: flutter build apk --release --split-per-abi #i.e device wise binary i.e x86,arm64 etc
      - run: flutter build apk --debug
      - name: Create a Release in GitHub
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/*.apk,build/app/outputs/bundle/release/app-release.aab"
          token: ${{ secrets.GH_TOKEN }}
#          tag: ${{ needs.job1.outputs.build_number }}
          tag: v0.1.${{ github.run_number }}
          commit: master
          prerelease: true